[package]
name = "starpsx"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", features = ["wgpu"] }
gilrs = "0.11.0"
starpsx-core = { path = "../core" }
tracing = "0.1.43"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "registry"] }

[features]
full-vram = ["starpsx-core/full-vram"]
