[package]
name = "starpsx"
version = "0.4.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
cpal = "0.17.1"
eframe = { version = "0.33.3", features = ["wgpu"] }
gilrs = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
starpsx-core = { path = "../core" }
starpsx-renderer = { path = "../renderer" }
toml = "0.9.11"
tracing = "0.1.43"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "registry"] }

[features]
full-vram = ["starpsx-core/full-vram"]
