[package]
name = "starpsx"
version = "0.1.0"
edition = "2024"

[dependencies]
starpsx-core = { path = "../core" }
starpsx-renderer = { path = "../renderer"}
softbuffer = "0.4.6"
winit = "0.30.12"
gilrs = "0.11.0"

[target.'cfg(windows)'.profile.release]
rustflags = ["-C", "link-args=/STACK:8388608"]
