[package]
name = "starpsx-core"
version = "0.1.0"
edition = "2024"

[dependencies]
starpsx-renderer = { path = "../renderer" }
arrayvec = "0.7.6"
bitfield = "0.19.1"
tracing = "0.1.43"

[features]
full-vram=["starpsx-renderer/full-vram"]
